// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zimzhfvxglhvhpkkgqbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppbXpoZnZ4Z2xodmhwa2tncWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTU3NjAsImV4cCI6MjA3NDQ5MTc2MH0.BbtYXwFX8SPJmJA9sRLt7wGvVV2wi253UdiDRbC5Y4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});